# Generated by Django 4.2.23 on 2025-08-07 11:21

import country.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50)),
                ('country_flag', models.FileField(upload_to=country.models.hashed_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('country_currency', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
    ]
